

function copyCode(blockNumber) {
  const codeBlock = document.querySelector(`.code-block:nth-child(${blockNumber})`);
  if (codeBlock) {
    const codeText = codeBlock.querySelector('pre').textContent;
    const copyButton = codeBlock.querySelector('.copy-button');

    // Create a textarea element inside the code block
    const textarea = document.createElement('textarea');
    textarea.value = codeText;
    codeBlock.appendChild(textarea); // Append the textarea to the code block

    textarea.select();
    document.execCommand('copy');

    // Remove the textarea from the code block after copying
    codeBlock.removeChild(textarea);

    // Display "Code Copied" with a tick mark and revert to "Copy Code" after 2 seconds
    copyButton.innerHTML = '<span class="tick-mark"></span> Code Copied';
    setTimeout(() => {
      copyButton.innerHTML = '📋 Copy Code';
    }, 2000);
  }
}


// Generated by CodiumAI

describe('copyCode', () => {

    // Displays "Code Copied" with a tick mark
    it('should display "Code Copied" with a tick mark', () => {
      // Arrange
      const blockNumber = 1;
      const codeBlock = document.createElement('div');
      codeBlock.classList.add('code-block');
      const pre = document.createElement('pre');
      pre.textContent = 'const x = 10;';
      codeBlock.appendChild(pre);
      const copyButton = document.createElement('button');
      copyButton.classList.add('copy-button');
      codeBlock.appendChild(copyButton);
      document.body.appendChild(codeBlock);

      // Act
      copyCode(blockNumber);

      // Assert
      expect(codeBlock.querySelector('.copy-button').innerHTML).toBe('<span class="tick-mark"></span> Code Copied');

      // Clean up
      document.body.removeChild(codeBlock);
    });
});
